/**
 * Maximal-length sequences (m-sequences) generated by a primitive polynomial.
 *
 * A degree-n primitive polynomial over GF(2) drives a Galois LFSR whose state
 * cycles through every nonzero n-bit word, giving a period of N = 2^n - 1.
 * The reciprocal polynomial is also primitive, so the Galois-tap convention
 * used here always yields a genuine m-sequence for a primitive mask.
 *
 * Bits are mapped to bipolar chips as chip = (-1)^bit, i.e. 0 -> +1, 1 -> -1.
 * Under this map, bitwise XOR corresponds to multiplying chips:
 *   (1-2b)(1-2c) = 1 - 2(b XOR c).
 */

/**
 * Generate one full m-sequence period as an Int8Array of +1/-1 chips.
 *
 * @param {bigint} polyMask primitive polynomial bit mask, bit n set
 * @param {number} n       LFSR degree
 * @returns {Int8Array}    length N = 2^n - 1
 */
export function generateMSequence(polyMask, n) {
  const N = 2 ** n - 1;
  const chips = new Int8Array(N);

  // Galois LFSR, left-shifting convention. The n-bit state represents a
  // remainder polynomial; a primitive characteristic polynomial makes its
  // nonzero states a single cycle of length N.
  //
  // Each step, output the high bit (x^(n-1) coefficient), shift left, and
  // when the high bit was 1 XOR the low n coefficients of the characteristic
  // polynomial f(x) = x^n + c_(n-1)x^(n-1) + ... + c_0 into the state
  // (reduction by f; c_0 = 1 for a primitive polynomial).
  const feedbackMask = Number(polyMask) & ((1 << n) - 1); // c_0..c_(n-1)
  const highBit = 1 << (n - 1);
  const stateMask = (1 << n) - 1;

  // Any nonzero initial state yields a phase of the same sequence.
  let state = stateMask; // all ones: fixed, phase-independent convention

  for (let i = 0; i < N; i += 1) {
    const output = state & highBit;
    chips[i] = output === 0 ? 1 : -1;
    state = (state << 1) & stateMask;
    if (output !== 0) state ^= feedbackMask;
  }

  return chips;
}

/** Bipolar product of two equal-length chip sequences: term by term multiply. */
export function multiplyChips(a, b) {
  const out = new Int8Array(a.length);
  for (let i = 0; i < a.length; i += 1) out[i] = a[i] * b[i];
  return out;
}

/** Copy with every chip polarity flipped. */
export function negateChips(a) {
  const out = new Int8Array(a.length);
  for (let i = 0; i < a.length; i += 1) out[i] = -a[i];
  return out;
}

/** Cyclic rotation by `shift` positions: out[k] = a[(k + shift) mod N]. */
export function rotateChips(a, shift) {
  const N = a.length;
  const s = ((shift % N) + N) % N;
  const out = new Int8Array(N);
  for (let i = 0; i < N; i += 1) out[i] = a[(i + s) % N];
  return out;
}
